apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Ursanon/argoflow.git
    targetRevision: HEAD
    path: .
    kustomize:
      version: v4.0.5
  destination:
    destination:
    name: in-cluster
    namespace: ''
    server: ''
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
