apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  source:
<<<<<<< HEAD
    repoURL: https://github.com/Ursanon/argoflow.git
=======
    repoURL: https://github.com/argoflow/argoflow
>>>>>>> upstream/master
    targetRevision: HEAD
    path: istio
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
