apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "Dqj5d0L+oqnWYWlgxqrHjrQ25M4vm9Krc2CpTmOvNhZMJKt8iujOWiVceUjo6rua\nD0cMiry1yaPz9j1c0i1s7PAthxUjuomlCqw+AfNZRC1kW7l7Femxb3G+UtAPvUbZ\n4FO8xAtpsYbazFgs9xW8BGXvx1OstorkrkbFy/Nt3zA="
