apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "xtla0EzDMyVMGsOZWTRYGPviOmFcicB2VIfsmRIm0R+Zm/xQsiuWKEB7gT0eC0Ac\nfiGFqYGmzjW9xaBQFEct0J72/0MLD8LkkwlU67u2qDQxdJ3uZS+riNItNM7TyMWN\nR2mDQHKgZ0e/OgY6fH5+3O5V/5CprJxsDdhyaaD0B7Q="
