apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "EIcNcX4tPzzKZDUlFB6jL0oKv6Id/6SiZCg29doFj8QvytYSdQ4HzyWcFGu2GNNr\ntZCyPJM3Nas9ZNpXWK85OgAwIcCzl0KDU2LDyRseN86IEMoHkjqA0ODkMldmD2Jz\nm/HUZu7sbgdq+JJ/Hj767iGcQWwl3y+Pkb0ITS5amW4="
