apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "MMiphVoCujewip355Czli/C8rQtisvMNxzOMcMkOxCqJxjMmZiS9WyL5vZ6iAa9S\nTS2EVhEptIRgIaVZuFm//CeUvCe2w93PryBlHVtRe1n6MV0hp8QPFbKBz8ZrSHFp\nIfUJ9EfF6l63aEHrMQQnw7wBHokVKE8pL1U0S6dIWvc="
