apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "D2cJ+f9x4K3ujZaxvQrXiwI5TnykKjDh2OalFxDRV3yGXs87xa2/vxxMd9xG0dPb\nqQ93DDDvng7nSrNUTjjL750pER+d105bZeUEDdE5QANUuxu8CQWTDlD7G1tZV3XQ\nyvPu0K3l/mLDEmamtryGxLWHz91VslDH11+zB8ucfQM="
