apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "LVXCe9B5yN9ndHXhXHtT04UGqQttz2C+oXwLSW5Z43bc9dGZiWOwH0PXZIJB33PD\nHD0z6qnSZDzWqmVv1ccNLsK1GJoujFZMoGsK6kqbhMss1fnxTNL90XMClTz/KAr+\ngXxZpO4rvRIme1VtUin37N6G64hnKboCwZcu+UJ6m4I="
