apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "4lLCOIEULAmxNdxROy7TA3YDhW+Xre27lwqlP83P/D2/X/KqsXWQIBrzcR2bhHFw\nE4JMjBiVkBRhWl7emNcggX3siFMXQXb6Iozsg0HhuLUn4ScvqmgyQe7H110y0JC7\nRDCamU0Xd+XgxI95LwO+U89MXE0dA1DJ+zaRsFL8BIc="
